(defrule a =>
	(bind ?socket (create-socket AF_INET SOCK_STREAM))
	(bind ?connection (connect ?socket 127.0.0.1 8888))
	(println "[CLIENT] Connected to " ?connection)
	(println "[CLIENT] Type a message to send to server")
	(printout t "[CLIENT] followed by the ENTER key: ")
	(bind ?msg (readline))
	(printout ?connection ?msg crlf)
	(println "[CLIENT] Wrote message. Waiting for response...")
	(flush-connection ?socket)
	(println "[CLIENT] The server said: " (readline ?connection))
)
(reset)
(run)
(exit)
