;;; (errno-sym) across every case in its switch.
;;;
;;; Only a handful of errnos are reachable by making real syscalls fail, so
;;; the rest are exercised through the optional argument form -- (errno-sym 13)
;;; names the value 13 without needing errno to actually be 13.
;;;
;;; The numbers below were generated from this platform's <errno.h>, so they
;;; are the values the switch is compiled against. tests/error/errno-symbols.clp
;;; covers the no-argument form against genuinely failed syscalls.

(load* "tests/lib/expect.clp")
(test-suite "errno-sym-cases")
(test-plan 130)

(deffunction check (?n ?expected)
   (expect-eq (str-cat "errno " ?n " is " ?expected) ?expected (errno-sym ?n)))

(deffunction run-tests ()
   (check 1 EPERM)
   (check 2 ENOENT)
   (check 3 ESRCH)
   (check 4 EINTR)
   (check 5 EIO)
   (check 6 ENXIO)
   (check 7 E2BIG)
   (check 8 ENOEXEC)
   (check 9 EBADF)
   (check 10 ECHILD)
   (check 11 EAGAIN)
   (check 12 ENOMEM)
   (check 13 EACCES)
   (check 14 EFAULT)
   (check 15 ENOTBLK)
   (check 16 EBUSY)
   (check 17 EEXIST)
   (check 18 EXDEV)
   (check 19 ENODEV)
   (check 20 ENOTDIR)
   (check 21 EISDIR)
   (check 22 EINVAL)
   (check 23 ENFILE)
   (check 24 EMFILE)
   (check 25 ENOTTY)
   (check 26 ETXTBSY)
   (check 27 EFBIG)
   (check 28 ENOSPC)
   (check 29 ESPIPE)
   (check 30 EROFS)
   (check 31 EMLINK)
   (check 32 EPIPE)
   (check 33 EDOM)
   (check 34 ERANGE)
   (check 35 EDEADLK)
   (check 36 ENAMETOOLONG)
   (check 37 ENOLCK)
   (check 38 ENOSYS)
   (check 39 ENOTEMPTY)
   (check 40 ELOOP)
   (check 42 ENOMSG)
   (check 43 EIDRM)
   (check 44 ECHRNG)
   (check 45 EL2NSYNC)
   (check 46 EL3HLT)
   (check 47 EL3RST)
   (check 48 ELNRNG)
   (check 49 EUNATCH)
   (check 50 ENOCSI)
   (check 51 EL2HLT)
   (check 52 EBADE)
   (check 53 EBADR)
   (check 54 EXFULL)
   (check 55 ENOANO)
   (check 56 EBADRQC)
   (check 57 EBADSLT)
   (check 59 EBFONT)
   (check 60 ENOSTR)
   (check 61 ENODATA)
   (check 62 ETIME)
   (check 63 ENOSR)
   (check 64 ENONET)
   (check 65 ENOPKG)
   (check 66 EREMOTE)
   (check 67 ENOLINK)
   (check 68 EADV)
   (check 69 ESRMNT)
   (check 70 ECOMM)
   (check 71 EPROTO)
   (check 72 EMULTIHOP)
   (check 73 EDOTDOT)
   (check 74 EBADMSG)
   (check 75 EOVERFLOW)
   (check 76 ENOTUNIQ)
   (check 77 EBADFD)
   (check 78 EREMCHG)
   (check 79 ELIBACC)
   (check 80 ELIBBAD)
   (check 81 ELIBSCN)
   (check 82 ELIBMAX)
   (check 84 EILSEQ)
   (check 85 ERESTART)
   (check 86 ESTRPIPE)
   (check 87 EUSERS)
   (check 88 ENOTSOCK)
   (check 89 EDESTADDRREQ)
   (check 90 EMSGSIZE)
   (check 91 EPROTOTYPE)
   (check 92 ENOPROTOOPT)
   (check 93 EPROTONOSUPPORT)
   (check 94 ESOCKTNOSUPPORT)
   (check 95 EOPNOTSUPP)
   (check 96 EPFNOSUPPORT)
   (check 97 EAFNOSUPPORT)
   (check 98 EADDRINUSE)
   (check 99 EADDRNOTAVAIL)
   (check 100 ENETDOWN)
   (check 101 ENETUNREACH)
   (check 102 ENETRESET)
   (check 103 ECONNABORTED)
   (check 104 ECONNRESET)
   (check 105 ENOBUFS)
   (check 106 EISCONN)
   (check 107 ENOTCONN)
   (check 108 ESHUTDOWN)
   (check 109 ETOOMANYREFS)
   (check 110 ETIMEDOUT)
   (check 111 ECONNREFUSED)
   (check 112 EHOSTDOWN)
   (check 113 EHOSTUNREACH)
   (check 114 EALREADY)
   (check 115 EINPROGRESS)
   (check 116 ESTALE)
   (check 117 EUCLEAN)
   (check 118 ENOTNAM)
   (check 119 ENAVAIL)
   (check 120 EISNAM)
   (check 121 EREMOTEIO)
   (check 122 EDQUOT)
   (check 123 ENOMEDIUM)
   (check 124 EMEDIUMTYPE)
   (check 125 ECANCELED)
   (check 126 ENOKEY)
   (check 127 EKEYEXPIRED)
   (check 128 EKEYREVOKED)
   (check 129 EKEYREJECTED)
   (check 130 EOWNERDEAD)
   (check 131 ENOTRECOVERABLE)
   (check 132 ERFKILL)
   (check 133 EHWPOISON)
)

;;; Values the switch does not recognise fall through to the default branch and
;;; return void. Void is legal as a statement but not as an argument, so these
;;; are called for effect only and are not counted in the plan.
(deffunction run-default-branch ()
   (errno-sym 0)
   (errno-sym 999999)
   (errno-sym -1))

(run-tests)
(run-default-branch)
(test-summary)
